# Generated by Django 4.2 on 2023-04-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Business Category')),
                ('contact_method', models.CharField(max_length=15, verbose_name='Contact Method')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Business Info',
                'verbose_name_plural': 'Business Infos',
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60, null=True, verbose_name='External ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(verbose_name='Modified Timestamp')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Last Scrpaed Timestamp')),
                ('scrape_count', models.IntegerField(default=0, verbose_name='Scrape Count')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Hashtag')),
            ],
            options={
                'verbose_name': 'Hashtag',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60, null=True, verbose_name='External ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(verbose_name='Modified Timestamp')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Last Scrpaed Timestamp')),
                ('scrape_count', models.IntegerField(default=0, verbose_name='Scrape Count')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Location Name')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60, null=True, verbose_name='External ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(verbose_name='Modified Timestamp')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Last Scrpaed Timestamp')),
                ('scrape_count', models.IntegerField(default=0, verbose_name='Scrape Count')),
                ('full_name', models.CharField(max_length=60, verbose_name='Full Name')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='Username')),
                ('biography', models.CharField(blank=True, max_length=300, null=True, verbose_name='Biography')),
                ('followers', models.IntegerField(blank=True, null=True, verbose_name='Followed By')),
                ('followees', models.IntegerField(blank=True, null=True, verbose_name='Follows')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profile Category')),
                ('profile_pic', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
                ('is_business', models.BooleanField(default=False, verbose_name='Is Business')),
                ('businsess_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_scraper.businessinfo', verbose_name='Business Info')),
            ],
            options={
                'verbose_name': 'Profile',
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60, null=True, verbose_name='External ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(verbose_name='Modified Timestamp')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Last Scrpaed Timestamp')),
                ('scrape_count', models.IntegerField(default=0, verbose_name='Scrape Count')),
                ('owner_username', models.CharField(max_length=60, verbose_name="Owner's Username")),
                ('likes_count', models.IntegerField(verbose_name='Likes Count')),
                ('comments_count', models.IntegerField(verbose_name='Comments Count')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('is_sponsored', models.BooleanField(default=False, verbose_name='Is Sponsored')),
                ('hashtags', models.ManyToManyField(blank=True, to='profile_scraper.hashtag')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profile_scraper.location')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profile_scraper.profile')),
            ],
            options={
                'verbose_name': 'Post',
                'ordering': ('likes_count', 'owner_username'),
            },
        ),
    ]
