# Generated by Django 4.2 on 2023-04-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='businsess_info',
            new_name='business_info',
        ),
    ]
