# Generated by Django 4.2 on 2023-04-05 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0003_alter_post_caption_alter_post_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtag',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Scrpaed Timestamp'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtag',
            name='scrape_count',
            field=models.IntegerField(default=0, verbose_name='Scrape Count'),
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Scrpaed Timestamp'),
        ),
        migrations.AddField(
            model_name='location',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='scrape_count',
            field=models.IntegerField(default=0, verbose_name='Scrape Count'),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Scrpaed Timestamp'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='scrape_count',
            field=models.IntegerField(default=0, verbose_name='Scrape Count'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Scrpaed Timestamp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='scrape_count',
            field=models.IntegerField(default=0, verbose_name='Scrape Count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='profile_scraper.hashtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profile_scraper.location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profile_scraper.profile'),
        ),
    ]
