# Generated by Django 4.2 on 2023-04-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0004_alter_profile_business_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp'),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp'),
        ),
    ]
