# Generated by Django 4.2 on 2023-04-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0005_alter_hashtag_title_alter_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_sponseored',
            new_name='is_sponsored',
        ),
    ]
