# Generated by Django 4.2 on 2023-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0006_rename_is_sponseored_post_is_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='external_id',
            field=models.CharField(max_length=60, null=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='external_id',
            field=models.CharField(max_length=60, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='external_id',
            field=models.CharField(max_length=60, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profile Category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.CharField(max_length=60, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Follows'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Followed By'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Picture'),
        ),
    ]
