# Generated by Django 4.2 on 2023-04-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0012_remove_profile_business_info_businessinfo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='business_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profile_scraper.businessinfo'),
        ),
    ]
