version: "3.8"

services:
  db:
    container_name: miner_postgres
    image: postgres:15.2-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bhms_miner
      - POSTGRES_PASSWORD=bhms_pass
      - POSTGRES_DB=bhms_chest
    ports:
      - 5432:5432

  redis:
    container_name: miner_redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  db_data:
