version: "3.8"

services:
  miner:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    command: sh /home/app/miner/start-django
    volumes:
      - static_volume:/home/app/miner/src/staticfiles
      - ./data:/home/app/miner/data
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    command: sh /home/app/miner/start-celeryworker
    volumes:
      - ./data:/home/app/miner/data
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    command: sh /home/app/miner/start-celerybeat
    volumes:
      - ./data:/home/app/miner/data
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - db

  db:
    image: postgres:15.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  redis:
    image: redis:7-alpine
    env_file:
      - ./.env.prod

  nginx:
    build: ./docker/production/nginx
    volumes:
      - static_volume:/home/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - miner

volumes:
  db_data:
  static_volume:
