version: "3.8"

services:
  miner_app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn bhms_miner.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/miner/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - miner_db
      - celery_backend

  miner_db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    volumes:
      - miner_db_data:${SQL_DATA_VOLUME}

  celery_backend:
    image: redis/redis-stack:latest
    container_name: bhms-celery-backend
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/miner/staticfiles
    ports:
      - 1337:80
    depends_on:
      - miner_app

volumes:
  miner_db_data:
  static_volume:
