# Generated by Django 4.2 on 2023-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0005_alter_hashtag_created_alter_hashtag_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_authentic_slug',
            field=models.BooleanField(default=True, verbose_name='Is Slug Authentic'),
        ),
    ]
