# Generated by Django 4.2 on 2023-04-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0007_alter_hashtag_external_id_alter_location_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='Slug'),
        ),
    ]
