# Generated by Django 4.2 on 2023-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0009_alter_businessinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'ordering': ('category',), 'verbose_name': 'Business Info'},
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Category'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='contact_method',
            field=models.CharField(default='UNKNOWN', max_length=50, verbose_name='Contact Method'),
        ),
    ]
