# Generated by Django 4.2 on 2023-04-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0010_alter_businessinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Profile Picture'),
        ),
    ]
